# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MSF.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tMSF.proto\x12\x03msf\"\xe6\x01\n\x04Note\x12\r\n\x05pitch\x18\x01 \x02(\r\x12\r\n\x05start\x18\x02 \x02(\r\x12\x10\n\x08\x64uration\x18\x03 \x02(\r\x12&\n\tattribute\x18\x04 \x03(\x0b\x32\x13.msf.Note.Attribute\x1a\x85\x01\n\tAttribute\x12&\n\x04type\x18\x01 \x02(\x0e\x32\x18.msf.Note.Attribute.Type\x12\r\n\x05value\x18\x02 \x02(\r\"A\n\x04Type\x12\r\n\tONSET_VEL\x10\x00\x12\x0e\n\nOFFSET_VEL\x10\x01\x12\n\n\x06LEGATO\x10\x02\x12\x0e\n\nPORTAMENTO\x10\x03\"\"\n\x07NoteSet\x12\x17\n\x04note\x18\x01 \x03(\x0b\x32\t.msf.Note\"\xf9\x01\n\x05Track\x12\x14\n\x0cinstrumentID\x18\x01 \x02(\r\x12\x1d\n\x04meta\x18\x02 \x03(\x0b\x32\x0f.msf.Track.Meta\x12\x17\n\x04note\x18\x03 \x03(\x0b\x32\t.msf.Note\x12)\n\tpitchBend\x18\x04 \x03(\x0b\x32\x16.msf.Track.TrackChange\x12&\n\x06volume\x18\x05 \x03(\x0b\x32\x16.msf.Track.TrackChange\x1a#\n\x04Meta\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\x1a*\n\x0bTrackChange\x12\x0c\n\x04time\x18\x01 \x02(\r\x12\r\n\x05value\x18\x02 \x02(\r\"\xcc\x02\n\x08Sequence\x12 \n\x04meta\x18\x01 \x03(\x0b\x32\x12.msf.Sequence.Meta\x12\x14\n\x0cquantization\x18\x02 \x02(\r\x12\x19\n\x05track\x18\x03 \x03(\x0b\x32\n.msf.Track\x12\x32\n\rtimeSignature\x18\x04 \x03(\x0b\x32\x1b.msf.Sequence.TimeSignature\x12\'\n\x03qpm\x18\x05 \x03(\x0b\x32\x1a.msf.Sequence.GlobalChange\x1a#\n\x04Meta\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\x1a+\n\x0cGlobalChange\x12\x0c\n\x04time\x18\x01 \x02(\r\x12\r\n\x05value\x18\x02 \x02(\r\x1a>\n\rTimeSignature\x12\x0c\n\x04time\x18\x01 \x02(\r\x12\r\n\x05\x62\x65\x61ts\x18\x02 \x02(\r\x12\x10\n\x08\x62\x65\x61tType\x18\x03 \x02(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MSF_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOTE._serialized_start=19
  _NOTE._serialized_end=249
  _NOTE_ATTRIBUTE._serialized_start=116
  _NOTE_ATTRIBUTE._serialized_end=249
  _NOTE_ATTRIBUTE_TYPE._serialized_start=184
  _NOTE_ATTRIBUTE_TYPE._serialized_end=249
  _NOTESET._serialized_start=251
  _NOTESET._serialized_end=285
  _TRACK._serialized_start=288
  _TRACK._serialized_end=537
  _TRACK_META._serialized_start=458
  _TRACK_META._serialized_end=493
  _TRACK_TRACKCHANGE._serialized_start=495
  _TRACK_TRACKCHANGE._serialized_end=537
  _SEQUENCE._serialized_start=540
  _SEQUENCE._serialized_end=872
  _SEQUENCE_META._serialized_start=458
  _SEQUENCE_META._serialized_end=493
  _SEQUENCE_GLOBALCHANGE._serialized_start=765
  _SEQUENCE_GLOBALCHANGE._serialized_end=808
  _SEQUENCE_TIMESIGNATURE._serialized_start=810
  _SEQUENCE_TIMESIGNATURE._serialized_end=872
# @@protoc_insertion_point(module_scope)
